# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Appcast < Formula
  desc "A CLI tool for signing update packages and creating appcast XML for use with Sparkle."
  homepage ""
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/abemedia/appcast/releases/download/v0.1.0/appcast_0.1.0_darwin_arm64"
      sha256 "ca8061d6efa658b76083627b3664ea3ad65f41735762bc352b29b8c88f4c4d56"

      def install
        bin.install "appcast_0.1.0_darwin_arm64" => "appcast"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/abemedia/appcast/releases/download/v0.1.0/appcast_0.1.0_darwin_amd64"
      sha256 "8699b28daca4bb148e1997962e73ad364896593b273ce15da7a9525b2b708a6d"

      def install
        bin.install "appcast_0.1.0_darwin_amd64" => "appcast"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/abemedia/appcast/releases/download/v0.1.0/appcast_0.1.0_linux_amd64"
      sha256 "3531f09bf548118b5492b4694e222031303ef663eb5e70b117caff7034b3fb2c"

      def install
        bin.install "appcast_0.1.0_linux_amd64" => "appcast"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/abemedia/appcast/releases/download/v0.1.0/appcast_0.1.0_linux_armv6"
      sha256 "e1ed8e457050befb109c5af85d8a45662d22a721a001cb055da42449249d6533"

      def install
        bin.install "appcast_0.1.0_linux_armv6" => "appcast"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abemedia/appcast/releases/download/v0.1.0/appcast_0.1.0_linux_arm64"
      sha256 "d24daa3234aa08caa5f132d1508ead7be9a52eddb5298764ac4cc0f1f3c241d1"

      def install
        bin.install "appcast_0.1.0_linux_arm64" => "appcast"
      end
    end
  end

  test do
    system "#{bin}/appcast version"
  end
end
