# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Appcast < Formula
  desc "A CLI tool for signing update packages and creating appcast XML for use with Sparkle."
  homepage ""
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abemedia/appcast/releases/download/v0.1.0/appcast_0.1.0_darwin_amd64"
      sha256 "06821a99816f72845f6db7cb2f5977546eccfce0cc867493a490293857a40a20"

      def install
        bin.install "appcast_0.1.0_darwin_amd64" => "appcast"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abemedia/appcast/releases/download/v0.1.0/appcast_0.1.0_darwin_arm64"
      sha256 "93b6a3d0f2d9bb367871c221f4033f5dd8bdfb9bf8496c9f4a9dcd37b220426c"

      def install
        bin.install "appcast_0.1.0_darwin_arm64" => "appcast"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/abemedia/appcast/releases/download/v0.1.0/appcast_0.1.0_linux_amd64"
      sha256 "b3aacb07636714a2022ba0b8cb0639c8f8f9444fbc265d07648a99ee3f43d5f6"

      def install
        bin.install "appcast_0.1.0_linux_amd64" => "appcast"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/abemedia/appcast/releases/download/v0.1.0/appcast_0.1.0_linux_armv6"
      sha256 "7671ac57c44acda8bab5e9372904a94dfa289716ef1761a3b4ca2ce8e8b963fa"

      def install
        bin.install "appcast_0.1.0_linux_armv6" => "appcast"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abemedia/appcast/releases/download/v0.1.0/appcast_0.1.0_linux_arm64"
      sha256 "ec0ccc213f95dad24d9ec733fe27c84484e3873331007867ce3fbf0e4cb206ba"

      def install
        bin.install "appcast_0.1.0_linux_arm64" => "appcast"
      end
    end
  end

  test do
    system "#{bin}/appcast version"
  end
end
